import * as WebSocket from "ws";

export interface Quote {
  0?: string,
  1?: number,
  2?: number,
  3?: number,
  4?: number,
  5?: number,
  6?: string,
  7?: string,
  8?: number,
  9?: number,
  10?: number,
  11?: number,
  12?: number,
  13?: number,
  14?: string,
  15?: number,
  16?: string,
  17?: boolean,
  18?: boolean,
  19?: number,
  20?: number,
  21?: number,
  22?: number,
  23?: number,
  24?: number,
  25?: string,
  26?: string,
  27?: number,
  28?: number,
  29?: number,
  30?: number,
  31?: number,
  32?: number,
  33?: number,
  34?: number,
  35?: number,
  36?: number,
  37?: number,
  38?: number,
  39?: string,
  40?: string,
  41?: boolean,
  42?: boolean,
  43?: number,
  44?: number,
  45?: number,
  46?: number,
  47?: number,
  48?: string,
  49?: number,
  50?: number,
  51?: number,
  52?: number,
  seq?: number,
  key?: string,
}

export interface Chart {
  0?: string,
  1?: number,
  2?: number,
  3?: number,
  4?: number,
  5?: number,
  6?: number,
  7?: number,
  8?: number,
  seq?: number,
  key?: string,
}

export interface Book {
  0?: string,
  1?: number,
  2?: number,
  3?: number,
  4?: number,
  5?: number,
  seq?: number,
  key?: string,
}

export interface TimeSales {
  0?: string,
  1?: number,
  2?: number,
  3?: number,
  4?: number,
  seq?: number,
  key?: string,
}

export interface SocketResponse {
  service: string,
  timestamp: number,
  command: string,
  content: Quote[] | TimeSales[] | Book[] | Chart[],
}

export interface MessageEvent extends WebSocket {
  data: SocketResponse[],
}